CREATE TABLE DELETED_COMMENTS (
  ID VARCHAR2(50),
  CONTENT CLOB,
  USERNAME VARCHAR2(100),
  POSTID VARCHAR2(50),
  CREATEDAT DATE,
  DELETED_AT DATE
);

select * from DELETED_COMMENTS;

select * from COMMENTS;